/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.util.ArrayList;

/**
 *
 * @author spencerdouglas
 */
public class EhhsistantGUI extends javax.swing.JPanel {
    Presentation selectedPresentation = null;
    ArrayList<Presentation> presentationList = new ArrayList<Presentation>(0);
    /**
     * Creates new form EhhsistantGUI
     */
    public EhhsistantGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainFrame = new javax.swing.JFrame();
        panelContainer = new javax.swing.JTabbedPane();
        recordPanel = new javax.swing.JPanel();
        createNewPresentionButton = new javax.swing.JButton();
        noPresentationSelectedLabel = new javax.swing.JLabel();
        selectPresentationButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        managePanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jOptionPane1 = new javax.swing.JOptionPane();
        createPresentationDialog = new javax.swing.JDialog();
        newPresentationNameLabel = new javax.swing.JLabel();
        selectPresentationDialog = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        selectPresentationDialogList = new javax.swing.JList<>();
        presentationDialogLabel = new javax.swing.JLabel();
        cancelPresentationSelectionButton = new javax.swing.JButton();
        confirmSelectionDialogButton = new javax.swing.JButton();

        mainFrame.setVisible(true);

        createNewPresentionButton.setText("Create New Presentation");
        createNewPresentionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewPresentionButtonActionPerformed(evt);
            }
        });

        noPresentationSelectedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noPresentationSelectedLabel.setText("<html>You currently have no presentation selected.  <br>To create a recording, first select or create a new presentation below.</html>");

        selectPresentationButton.setText("Select Presentation");
        selectPresentationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectPresentationButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Record");

        jButton2.setText("Pause");

        jButton3.setText("Stop");

        jButton4.setText("Delete Recording");

        javax.swing.GroupLayout recordPanelLayout = new javax.swing.GroupLayout(recordPanel);
        recordPanel.setLayout(recordPanelLayout);
        recordPanelLayout.setHorizontalGroup(
            recordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recordPanelLayout.createSequentialGroup()
                .addGroup(recordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(recordPanelLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(recordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(recordPanelLayout.createSequentialGroup()
                                .addComponent(createNewPresentionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(selectPresentationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(noPresentationSelectedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(recordPanelLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        recordPanelLayout.setVerticalGroup(
            recordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recordPanelLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(noPresentationSelectedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(recordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(recordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton3)
                        .addComponent(jButton4))
                    .addGroup(recordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 326, Short.MAX_VALUE)
                .addGroup(recordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createNewPresentionButton)
                    .addComponent(selectPresentationButton))
                .addGap(51, 51, 51))
        );

        noPresentationSelectedLabel.setVisible(presentationList == null);

        panelContainer.addTab("Record Presentation", recordPanel);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList3);

        javax.swing.GroupLayout managePanelLayout = new javax.swing.GroupLayout(managePanel);
        managePanel.setLayout(managePanelLayout);
        managePanelLayout.setHorizontalGroup(
            managePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managePanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        managePanelLayout.setVerticalGroup(
            managePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(managePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(331, Short.MAX_VALUE))
        );

        panelContainer.addTab("Manage Presentations", managePanel);

        javax.swing.GroupLayout mainFrameLayout = new javax.swing.GroupLayout(mainFrame.getContentPane());
        mainFrame.getContentPane().setLayout(mainFrameLayout);
        mainFrameLayout.setHorizontalGroup(
            mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainFrameLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        mainFrameLayout.setVerticalGroup(
            mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContainer)
        );

        newPresentationNameLabel.setText("Presentation Name:");

        javax.swing.GroupLayout createPresentationDialogLayout = new javax.swing.GroupLayout(createPresentationDialog.getContentPane());
        createPresentationDialog.getContentPane().setLayout(createPresentationDialogLayout);
        createPresentationDialogLayout.setHorizontalGroup(
            createPresentationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPresentationDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newPresentationNameLabel)
                .addContainerGap(337, Short.MAX_VALUE))
        );
        createPresentationDialogLayout.setVerticalGroup(
            createPresentationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPresentationDialogLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(newPresentationNameLabel)
                .addContainerGap(387, Short.MAX_VALUE))
        );

        String[] stringArr = new String[presentationList.size()];
        for (int i = 0; i < presentationList.size(); i++) {
            stringArr[i] = presentationList.get(i).toString();
        }
        selectPresentationDialogList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = stringArr;
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(selectPresentationDialogList);

        presentationDialogLabel.setText("Please select a presentation from the list below.");

        cancelPresentationSelectionButton.setText("Cancel");

        confirmSelectionDialogButton.setText("Select Presentation");

        javax.swing.GroupLayout selectPresentationDialogLayout = new javax.swing.GroupLayout(selectPresentationDialog.getContentPane());
        selectPresentationDialog.getContentPane().setLayout(selectPresentationDialogLayout);
        selectPresentationDialogLayout.setHorizontalGroup(
            selectPresentationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectPresentationDialogLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(selectPresentationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(presentationDialogLabel)
                    .addGroup(selectPresentationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, selectPresentationDialogLayout.createSequentialGroup()
                            .addComponent(cancelPresentationSelectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(confirmSelectionDialogButton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        selectPresentationDialogLayout.setVerticalGroup(
            selectPresentationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectPresentationDialogLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(presentationDialogLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(selectPresentationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelPresentationSelectionButton)
                    .addComponent(confirmSelectionDialogButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selectPresentationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectPresentationButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectPresentationButtonActionPerformed

    private void createNewPresentionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewPresentionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createNewPresentionButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelPresentationSelectionButton;
    private javax.swing.JButton confirmSelectionDialogButton;
    private javax.swing.JButton createNewPresentionButton;
    private javax.swing.JDialog createPresentationDialog;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JFrame mainFrame;
    private javax.swing.JPanel managePanel;
    private javax.swing.JLabel newPresentationNameLabel;
    private javax.swing.JLabel noPresentationSelectedLabel;
    private javax.swing.JTabbedPane panelContainer;
    private javax.swing.JLabel presentationDialogLabel;
    private javax.swing.JPanel recordPanel;
    private javax.swing.JButton selectPresentationButton;
    private javax.swing.JDialog selectPresentationDialog;
    private javax.swing.JList<String> selectPresentationDialogList;
    // End of variables declaration//GEN-END:variables
    /**
     * @param args the command line arguments
     */


}
